### ISSUE TITLE
Update RCW 46.52.070(2) and (3): Police officer's report

### ISSUE THREAD

**Issue by rcphilbr** [gaites/av-guidance#10]
In addition to identity of operator under (2)(b), officer to include in report to department relevant information to facilitate use of data from Event Data Reporter in vehicle.

Clarify (3)(b) to comport with DUI and operator competency updates.

**Comment by rcphilbr** [comment]
Add to Aida's section on administration?

**Comment by gaites** [comment]
I've got this right now as a separate amendatory section. Let me know if this needs to change for some reason.

**Comment by gaites** [comment]
resolved by dffabd0f1868bb9dd180cf9e8d7c920ea0c1c842
