### ISSUE TITLE
Definitions of "Driver" and "Operator"

### ISSUE THREAD

**Issue by claw2** [gaites/av-guidance#12]
We need to check the other RCW's that deal with driving and being in control of a car, just to check whether the law currently interchanges "driver" and "operator" in ways that might make our definitions confusing.

**Comment by gaites** [comment]
Also need to gel "physical control" with the issues here.

**Comment by gaites** [comment]
I included the word "physical control" but we need to figure out the scheme to make it work.

**Comment by gaites** [comment]
We need to make the language and definition consistent across the legislation and justifications.

**Comment by gaites** [comment]
Also need to make the "engager" separate from the occupants.

**Comment by gaites** [comment]
maybe refine to use "dynamic driving task"

**Comment by claw2** [comment]
"Any person who engages a level 4 or higher AV capability shall not be considered a 'driver', 'operator', or 'in control of a vehicle'"

"Any person who engages a level 3 or lower AV capability shall be considered the 'dynamic driver' but shall not be considered a 'driver', 'operator', or 'in control of a vehicle'"

**Comment by gaites** [comment]
Resolved under aeb67d600f89291c04e192426b7e8729c5404776
