### ISSUE TITLE
Include SAE standards in definition?

### ISSUE THREAD

**Issue by gaites** [gaites/av-guidance#2]
Should the SAE definitions be included directly into the definitions file?

**Comment by gaites** [comment]
Change request #3 addresses this issue, and includes the appropriate changes.

**Comment by rcphilbr** [comment]
The Google attorney we talked to the other day seemed to be using the SAE levels 0-4, not the NHTSA levels 0-5. Is one in more common usage? My opinion is we should just use one, but explain why not the other. SAE is international, so for WA legislation the NHTSA levels make most sense to me.

**Comment by gaites** [comment]
The Google attorney was definitely using levels 0-4, I'm not sure why exactly. The Society of Automotive Engineers (SAE) lists [0-5](http://www.sae.org/misc/pdfs/automated_driving.pdf). NHTSA references the SAE guidelines for their guidance document as well. It seems to be the de facto standard for automation. That's why I thought that the SAE would be the most consistent standard. We could reference it as the NHTSA standard, it would come out the same. 

I would also be concerned about creating our own definition or turning to a different standard. I feel like it could cause problems between agency competencies, manufacturers, and conflict between states. I'm not sure that we could put off actually including a codification of the automation standards. -- I know legislating the technology isn't always advisable, but I think this might be one situation where it meets our needs.

**Comment by gaites** [comment]
resolved in 3b6a9e9a1a904f8bf79e907e580110a747f0eacc
