### ISSUE TITLE
Registration/Pre-Clearance

### ISSUE THREAD

**Issue by claw2** [gaites/av-guidance#23]
Look into the idea of having the deployment requirements be relatively minimized so that they are less of a pre-clearance regime and more of a certification that the vehicle has AV capabilities.  The idea being that cars with AV can be put on the road without getting pre-clearance from the DOL ahead of time (this solves the state reciprocity problem and opens the market) and instead just issues registrations based on which SAE level the vehicle falls into.

The problem that remains, however, is what would stop manufacturers from simply ignoring the "Testing Phase" requirements and saying they started in the "Deployment Phase".  There is also the "wild west" problem, where less responsible actors or hobbyists could put AV's onto the road with no insurance or bonding and then end up being judgment-proof parties.

**Comment by gaites** [comment]
What if we still have a pre-clearance mechanism, but just make the burden light. It might look something like this:

1. A manufacturer of a vehicle with autonomous functionality may submit a licensing request to the dep't
   - The dep't will review: bonding and testing procedures for that vehicle (as a test of sufficiency)
      - Following and successfully completing the in-state testing regime is an automatic pass
   - The dep't should give deference to manufacturer's certification of SAE level
   - This approval would work for all vehicles of that model
2. An upfitter of a vehicle may submit a licensing request to the dep't
   - The dep't will review: bonding, testing, etc
     - Following in-state testing regime is an automatic pass
   - The dep't may authorize that upfitter to upfit vehicles of a specific make and model
3. A hobbyist (individual) may for non-commercial purposes operate a vehicle which they have personally modified. 
   - They do not require dep't licensing to upfit a personal vehicle, but must carry insurance equal to commercial vehicle operation req's
   - fines and penalties for failure to get licensing if used commercially

**Comment by claw2** [comment]
I just had an idea.  What if we set it up on a timeline/miles driven (whichever comes first) situation?

That way, initial entrants onto the market have to have $5mil in bonding and must have a certified driver behind the wheel at all times and get a "Testing" sticker on their registration.  After holding such a status for, let's say, two years of showing that their tech is safer than a human driver (or x million miles driven, whichever comes first), they can then apply for a "Deployment" registration, which lowers the bonding requirement to (whatever we set) and doesn't require the certified driver anymore.  Any autonomous car without a sticker has strict liability for any incidents and isn't exempt from DUI laws, etc. AND we could create criminal liabilities if their tech was foreseeably below the industry standards.  That way, hobbyists do it at their own risk, with strict liability and there are incentives to actually adhere to the testing procedures.

**Comment by gaites** [comment]
The hard problem with that is that the 2 year standard (or other hard restriction) might be too much time, especially if we're thinking in the context of a make or model. For example, the Tesla software won't change substantially between models (even though there might be some small differences). I'm sure it does need to adjust for new inputs and variations in model size and so forth, but I would bet that those changes are fairly minimal.

I like keeping options open, so maybe this would work in combination with a DoL independent review "sufficiency of testing" kind of deal?

**Comment by claw2** [comment]
"What is your timeline/miles driven for getting out of beta?"  My thought was that since we'd be pairing it with a miles-driven alternative, we'd want a longer timeline that way less scrupulous manufacturers couldn't just wait out the testing requirements (which might happen if it were six months or even just a year).  I do like adding the third prong, though.  So that manufacturers either have to:
(1) have it in a minimum testing regime for X years or more with a rate of fewer than Y accidents in Z miles driven, 
(2) certify that it drove X miles (which would have to be substantially higher than the Z miles driven under the first condition) with fewer than Y accidents per mile over that timeline, or
(3) complete a DOL-approved testing regime

Aside from the technical

**Comment by gaites** [comment]
@claw2 Ok, I like that idea, but we should be careful to permit flexible requirements, so maybe delegate to the dep't specific *kinds* of regulations they must develop, but not the actual content of them, especially for your 1 and 2.

**Comment by gaites** [comment]
Questions resolved in aeb67d600f89291c04e192426b7e8729c5404776
