### ISSUE TITLE
Privacy requirements to DOL

### ISSUE THREAD

**Issue by ajoaco** [gaites/av-guidance#26]
I would suggest a one-stop shop model to comply with the privacy requirement.

The companies can send the report to the DOL, along with the rest of papers for the testing licensing, and the DOL would then forward it to the Chief Privacy Officer. thus making life easier to companies.

I also think that we should have to different privacy statement requirements, as I wrote in the other issue. 

If you like the idea, I can add those references to the privacy policy in the test and operation parts. Tell me your thoughts.

Thanks.

**Comment by gaites** [comment]
One stop shop I think offers some good opportunities to streamline. Let's see what we can do to make it reasonable.

**Comment by gaites** [comment]
Fixed in aeb67d600f89291c04e192426b7e8729c5404776
